### ISSUE TITLE
BUG: compilation failed with "cannot assign twice to immutable variable `record_count`" error

### ISSUE THREAD

**Issue by vitali2y** [dathere/qsv#2324]
**Describe the bug**
Compilation [from source](https://github.com/dathere/qsv?tab=readme-ov-file#option-4-compile-from-source) with `feature_capable,apply,luau,foreach,to,self_update,polars,lite,datapusher_plus` optional features produces ```cannot assign twice to immutable variable `record_count` ``` error @ `src/cmd/sortcheck.rs:126`.

**To Reproduce**
```
➜  git clone https://github.com/dathere/qsv.git && cd qsv
~...~
➜  cargo build --release --locked --bin qsv --features feature_capable,apply,luau,foreach,to,self_update,polars,lite,datapusher_plus
    Updating git repository `https://github.com/pola-rs/polars`
  Downloaded time-macros v0.2.19
  Downloaded time v0.3.37
~...~
   Compiling polars-mem-engine v0.44.2 (https://github.com/pola-rs/polars?rev=d86e44b#d86e44b9)
   Compiling polars-sql v0.44.2 (https://github.com/pola-rs/polars?rev=d86e44b#d86e44b9)
~...~
error[E0384]: cannot assign twice to immutable variable `record_count`
   --> src/cmd/sortcheck.rs:126:9
    |
115 | /         record_count = if show_progress {
116 | |             let count = util::count_rows(&rconfig)?;
117 | |             util::prep_progress(&progress, count);
118 | |             count
...   |
121 | |             0
122 | |         };
    | |_________- first assignment to `record_count`
...
126 |           record_count = 0;
    |           ^^^^^^^^^^^^^^^^ cannot assign twice to immutable variable
    |
help: consider making this binding mutable
    |
105 |     let mut record_count;
    |         +++

For more information about this error, try `rustc --explain E0384`.
warning: `qsv` (bin "qsv") generated 3 warnings
error: could not compile `qsv` (bin "qsv") due to 1 previous error; 3 warnings emitted
➜
```

**Expected behavior**
Compilation should be finished successfully.

**Desktop:**
 - OS: Linux Mint 21.2
 - qsv Version 1.0.0 (`master` branch)
 - Rust: rustc 1.83.0 (90b35a623 2024-11-26)

**Comment by jqnatividad** [comment]
Hi @vitali2y ,
Thanks for the report.
However, this is by design.

The `datapusher_plus` feature is only meant to be used with the `luau` command at most and triggers the `qsvdp` binary variant to be built. 

It is MUTUALLY EXCLUSIVE with the `feature_capable` feature, which triggers the `qsv` binary variant to be built.

The `lite` feature builds the slimmed down `qsvlite` binary variant, and is also mutually exclusive with the `feature_capab;e` and `lite` features.

I'll update the documentation to make this clearer.

So for what you're trying to do, your build command should be as follows:

```
cargo build --release -F feature_capable,apply,luau,foreach,to,self_update,polars
```

**Comment by jqnatividad** [comment]
FYI @vitali2y 
Amended the docs as explained above
https://github.com/dathere/qsv/commit/83cd732b9180a218b0b5ed0154f1c735b0e58751
